networks:
  custom_network:
    driver: bridge

services:
  notes_app:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes_app
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: mysql
      MYSQL_PORT: $MYSQL_PORT
      UTH_USERNAME: $UTH_USERNAME
      UTH_PASSWORD: $UTH_PASSWORD
      FERNET_KEY: $FERNET_KEY
    ports:
      - "9000:9000"
    volumes:
      - "./backend:/app"
      - "/dev/net:/dev/net"
    cap_add:
      - NET_ADMIN
    networks:
      - custom_network
    devices:
      - /dev/net/tun

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - custom_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: $MYSQL_PORT
    ports:
      - "8080:80"
    networks:
      - custom_network
